# GitHub Actions Workflow for deploying a Node.js app to Azure Web App
#
# This workflow builds and deploys a Node.js app when changes are pushed to the "dev" branch.
# Ensure the AZURE_WEBAPP_PUBLISH_PROFILE secret is configured in your repository.

on:
  push:
    branches: 
      - "dev"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: CLASSROOM-SYSTEM-CLIENT    # Replace with your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'               # Path to your app; defaults to the repo root
  NODE_VERSION: '18.16.1'                      # Node.js version to use

permissions:
  contents: read

jobs:
  build:
    name: Build Node.js App
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install dependencies, build, and test
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build --if-present

      - name: Run Tests (if any)
        run: |
          npm run test --if-present

      # Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy to Azure Web App
    needs: build
    runs-on: ubuntu-latest  
    steps:
      # Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: node-app  
      # Deploy to Azure Web App
      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        